// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi3Rr5yn45e76fPx6aRucIbjgM4mnaICY',
    appId: '1:234791930437:web:aded041e856ee32ac0f12c',
    messagingSenderId: '234791930437',
    projectId: 'instriq-53015',
    authDomain: 'instriq-53015.firebaseapp.com',
    storageBucket: 'instriq-53015.firebasestorage.app',
    measurementId: 'G-37BMGVB73B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC36T7nTPcGbc9xDKkJrpI373riBdd1rkc',
    appId: '1:234791930437:android:9b085ea951129d01c0f12c',
    messagingSenderId: '234791930437',
    projectId: 'instriq-53015',
    storageBucket: 'instriq-53015.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnrmEtR5VQ0Suyr193BY2zABiFihDqz5I',
    appId: '1:234791930437:ios:a09d8542f3c19de6c0f12c',
    messagingSenderId: '234791930437',
    projectId: 'instriq-53015',
    storageBucket: 'instriq-53015.firebasestorage.app',
    iosBundleId: 'com.instriq.instriq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi3Rr5yn45e76fPx6aRucIbjgM4mnaICY',
    appId: '1:234791930437:web:599db72a776f8958c0f12c',
    messagingSenderId: '234791930437',
    projectId: 'instriq-53015',
    authDomain: 'instriq-53015.firebaseapp.com',
    storageBucket: 'instriq-53015.firebasestorage.app',
    measurementId: 'G-R3YCK98JR5',
  );
}
